# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYQQpOXlTpF6uaEFnTdfSsqby0ZFswOM
"""

import streamlit as st

# Configuração da página
st.set_page_config(page_title="Calculadora IRRF 2026", page_icon="💰")

st.title("💰 Calculadora de Salário Líquido 2026")
st.markdown("Com base nas novas regras de isenção até R$ 5.000,00 (SECOM).")

# Sidebar para entradas do usuário
with st.sidebar:
    st.header("Configurações")
    salario_bruto = st.number_input("Salário Bruto (R$):", min_value=0.0, value=5001.0, step=100.0)
    dependentes = st.number_input("Número de Dependentes:", min_value=0, value=0, step=1)

# --- LÓGICA DE CÁLCULO (A mesma que validamos) ---

# 1. INSS
if salario_bruto <= 1621.00:
    inss = (salario_bruto * 0.075)
elif salario_bruto <= 2902.84:
    inss = (salario_bruto * 0.09) - 24.32
elif salario_bruto <= 4354.27:
    inss = (salario_bruto * 0.12) - 111.40
else:
    valor_base_inss = min(salario_bruto, 8475.55)
    inss = (valor_base_inss * 0.14) - 198.49

# 2. Melhor Dedução (Simplificado vs Legal)
deducao_dep = dependentes * 189.59
deducoes_legais = inss + deducao_dep
desconto_simp = 607.20

escolha_simplificado = desconto_simp > deducoes_legais
melhor_deducao = max(deducoes_legais, desconto_simp)
base_irrf = max(0, salario_bruto - melhor_deducao)

# 3. IRRF Tabela Progressiva
if base_irrf <= 2428.80:
    irrf_bruto = 0
elif base_irrf <= 2826.65:
    irrf_bruto = (base_irrf * 0.075) - 182.16
elif base_irrf <= 3751.05:
    irrf_bruto = (base_irrf * 0.15) - 394.16
elif base_irrf <= 4664.68:
    irrf_bruto = (base_irrf * 0.225) - 675.49
else:
    irrf_bruto = (base_irrf * 0.275) - 908.73

# 4. Redutor SECOM 2026
redutor_2026 = 0
if 5000.00 < salario_bruto <= 7350.00:
    redutor_2026 = 978.62 - (0.133145 * salario_bruto)
elif salario_bruto <= 5000.00:
    redutor_2026 = irrf_bruto

irrf_final = max(0, irrf_bruto - redutor_2026)
salario_liquido = salario_bruto - inss - irrf_final

# --- INTERFACE DE RESULTADOS ---

col1, col2, col3 = st.columns(3)
col1.metric("Salário Líquido", f"R$ {salario_liquido:,.22f}")
col2.metric("INSS", f"R$ {inss:,.2f}")
col3.metric("IRRF Final", f"R$ {irrf_final:,.2f}")

st.divider()

with st.expander("Ver detalhes do cálculo"):
    st.write(f"**Base de Cálculo IR:** R$ {base_irrf:,.2f}")
    st.write(f"**Modelo aplicado:** {'Desconto Simplificado' if escolha_simplificado else 'Deduções Legais'}")
    st.write(f"**Imposto Bruto:** R$ {irrf_bruto:,.2f}")
    st.write(f"**Benefício/Redutor 2026:** R$ {redutor_2026:,.2f}")

st.info("Nota: Este cálculo utiliza as faixas estimadas para 2026 conforme o portal gov.br.")